USE [AirtravelBronze2]
GO

/****** Object:  View [dbo].[v_Airports]    Script Date: 28-10-25 14:26:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE   VIEW [dbo].[v_Airports]
AS 
SELECT 
    CAST([AIRPORT_SEQ_ID] AS INT) AS [AIRPORT_SEQ_ID]
    ,CAST([AIRPORT_ID] AS INT) AS [AIRPORT_ID]
    ,CAST([AIRPORT] AS NVARCHAR(3)) AS [AIRPORT]
    ,CAST([DISPLAY_AIRPORT_NAME] AS NVARCHAR(100)) AS [DISPLAY_AIRPORT_NAME]
    ,CAST([DISPLAY_AIRPORT_CITY_NAME_FULL] AS NVARCHAR(100)) AS [DISPLAY_AIRPORT_CITY_NAME_FULL]
    ,CAST([AIRPORT_WAC] AS INT) AS [AIRPORT_WAC]
    ,CAST([AIRPORT_COUNTRY_NAME] AS NVARCHAR(200)) AS [AIRPORT_COUNTRY_NAME]
    ,CAST([AIRPORT_COUNTRY_CODE_ISO] AS NVARCHAR(10)) AS [AIRPORT_COUNTRY_CODE_ISO]
    ,CAST([AIRPORT_STATE_NAME] AS NVARCHAR(200)) AS [AIRPORT_STATE_NAME]
    ,CAST([AIRPORT_STATE_CODE] AS NVARCHAR(10)) AS [AIRPORT_STATE_CODE]
    ,CAST([AIRPORT_STATE_FIPS] AS INT) AS [AIRPORT_STATE_FIPS]
    ,CAST([CITY_MARKET_ID] AS INT) AS [CITY_MARKET_ID]
    ,CAST([DISPLAY_CITY_MARKET_NAME_FULL] AS NVARCHAR(100)) AS [DISPLAY_CITY_MARKET_NAME_FULL]
    ,CAST([CITY_MARKET_WAC] AS INT) AS [CITY_MARKET_WAC]
    -- Colonnes de Coordonnées DMS
    ,CAST([LAT_DEGREES] AS INT) AS [LAT_DEGREES]
    ,CAST([LAT_HEMISPHERE] AS NCHAR(1)) AS [LAT_HEMISPHERE]
    ,CAST([LAT_MINUTES] AS INT) AS [LAT_MINUTES]
    ,CAST([LAT_SECONDS] AS INT) AS [LAT_SECONDS]
    -- Colonne LATITUDE Décimale
    ,CAST(
        [LATITUDE] / 100000000.0
        AS DECIMAL(9, 6) 
    ) AS [LATITUTE]
    -- Colonnes de Coordonnées DMS
    ,CAST([LON_DEGREES] AS INT) AS [LON_DEGREES]
    ,CAST([LON_HEMISPHERE] AS NCHAR(1)) AS [LON_HEMISPHERE]
    ,CAST([LON_MINUTES] AS INT) AS [LON_MINUTES]
    ,CAST([LON_SECONDS] AS INT) AS [LON_SECONDS]

    -- Colonne LONGITUDE Décimale
    ,CAST(
        [LONGITUDE] / 100000000.0
        AS DECIMAL(9, 6) 
    ) AS [LONGITUDE]

    -- Colonnes de Dates et Booléens
    ,CAST([AIRPORT_START_DATE] AS DATETIME2(7)) AS [AIRPORT_START_DATE]
    ,CAST([AIRPORT_THRU_DATE] AS DATETIME2(7)) AS [AIRPORT_THRU_DATE] 
    ,CAST([AIRPORT_IS_CLOSED] AS BIT) AS [AIRPORT_IS_CLOSED]
    ,CAST([AIRPORT_IS_LATEST] AS BIT) AS [AIRPORT_IS_LATEST]
FROM 
    T_MASTER_CORD;
GO

