USE [AirtravelBronze2]
GO

/****** Object:  View [dbo].[v_DB1]    Script Date: 03-11-25 10:03:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER   VIEW [dbo].[v_DB1] AS (
SELECT 
    CAST(DB1.MKT_ID AS BIGINT) AS MKT_ID   --- Unique ID
    , CAST(CONCAT (DB1.QUARTER, '-',DB1.YEAR,'-',DB1.ORIGIN_AIRPORT_SEQ_ID,'-', DB1.DEST_AIRPORT_SEQ_ID ) AS NVARCHAR(100)) AS QYEAR_ORI_DEST
    , CAST(ORIGIN_AIRPORT_SEQ_ID AS INT) AS ORIGIN_AIRPORT_SEQ_ID
    , CAST(DEST_AIRPORT_SEQ_ID AS INT) AS DEST_AIRPORT_SEQ_ID
    , CAST(
        CASE 
            WHEN DB1.OPERATING_CARRIER IS NULL OR DB1.OPERATING_CARRIER = '--' THEN '99'
            ELSE DB1.OPERATING_CARRIER
        END 
        AS NVARCHAR(3)
    ) AS UNIQUE_CARRIER 
    , CAST(CONCAT (DB1.QUARTER, DB1.YEAR) AS INT) AS QUARTER_YEAR
    , DB1.MARKET_FARE
    , DB1.MARKET_DISTANCE
FROM 
    DB1B_MARKET AS DB1
)
GO


