USE [AirtravelBronze]
GO

CREATE OR ALTER VIEW v_Aircrafts_Type
AS
SELECT 
AIRCRAFT_TYPE
,CASE
    WHEN LEN(AIRCRAFT_TYPE) = 4 THEN LEFT(AIRCRAFT_TYPE, 3)
    WHEN LEN(AIRCRAFT_TYPE) = 3 THEN LEFT(AIRCRAFT_TYPE, 3)
    ELSE AIRCRAFT_TYPE
END AS AIRCRAFT_TYPE_LOOKUP 
,CASE
    WHEN MANUFACTURER LIKE 'Airbus%' THEN 'AIRBUS'
    WHEN MANUFACTURER LIKE 'Boeing%' OR MANUFACTURER IN ('THEBOEINGCO', 'TheBoeingCompany') THEN 'BOEING'
    WHEN MANUFACTURER LIKE 'Bombardier%' THEN 'BOMBARDIER'
    WHEN MANUFACTURER LIKE 'Canadair%' THEN 'BOMBARDIER'
    WHEN MANUFACTURER LIKE 'GE' THEN 'BOMBARDIER'
    WHEN MANUFACTURER LIKE 'McDonnell%' OR MANUFACTURER LIKE 'Douglas%' THEN 'MCDONNELL DOUGLASS'
    WHEN MANUFACTURER LIKE 'DASSAULT%' OR MANUFACTURER IN ('Dassault') THEN 'DASSAULT'
    WHEN MANUFACTURER LIKE 'PIPISTRELDOO%' OR MANUFACTURER IN ('PIPISTRELDOO') THEN 'PIPISTREL'
    ELSE UPPER(MANUFACTURER)
END AS MANUFACTURER
FROM T_F41SCHEDULE_B43
WHERE (CONCAT(CAST(AIRCRAFT_TYPE AS VARCHAR),MANUFACTURER) NOT LIKE '7751Gulfstream')
AND (CONCAT(CAST(AIRCRAFT_TYPE AS VARCHAR),MANUFACTURER) NOT LIKE '6481Raytheon')
GROUP BY AIRCRAFT_TYPE
,CASE
    WHEN LEN(AIRCRAFT_TYPE) = 4 THEN LEFT(AIRCRAFT_TYPE, 3) -- Si 4 chiffres, on prend les 3 premiers
    WHEN LEN(AIRCRAFT_TYPE) = 3 THEN AIRCRAFT_TYPE           -- Si 3 chiffres, on ne fait rien
    ELSE AIRCRAFT_TYPE                                      -- Pour toute autre longueur (sécurité)
END
,
CASE
    WHEN MANUFACTURER LIKE 'Airbus%' THEN 'AIRBUS'
    WHEN MANUFACTURER LIKE 'Boeing%' OR MANUFACTURER IN ('THEBOEINGCO', 'TheBoeingCompany') THEN 'BOEING'
    WHEN MANUFACTURER LIKE 'Bombardier%' THEN 'BOMBARDIER'
    WHEN MANUFACTURER LIKE 'Canadair%' THEN 'BOMBARDIER'
    WHEN MANUFACTURER LIKE 'GE' THEN 'BOMBARDIER'
    WHEN MANUFACTURER LIKE 'McDonnell%' OR MANUFACTURER LIKE 'Douglas%' THEN 'MCDONNELL DOUGLASS'
    WHEN MANUFACTURER LIKE 'DASSAULT%' OR MANUFACTURER IN ('Dassault') THEN 'DASSAULT'
    WHEN MANUFACTURER LIKE 'PIPISTRELDOO%' OR MANUFACTURER IN ('PIPISTRELDOO') THEN 'PIPISTREL'
    ELSE UPPER(MANUFACTURER)

END
GO