USE [AirtravelBronze]
GO

/****** Object:  View [dbo].[v_Aircrafts]    Script Date: 28-10-25 14:26:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE   VIEW [dbo].[v_Aircrafts]
AS
SELECT --[YEAR]
--      ,[CARRIER]
        CAST(CONCAT([UNIQUE_CARRIER],'-',[SERIAL_NUMBER],'-',[TAIL_NUMBER]) AS NVARCHAR(50)) AS BK_ID
        ,CAST([SERIAL_NUMBER] AS NVARCHAR(40)) AS [SERIAL_NUMBER]
        ,CAST([TAIL_NUMBER] AS NVARCHAR(10)) AS [TAIL_NUMBER]
        ,CAST([UNIQUE_CARRIER] AS NVARCHAR(5)) AS [UNIQUE_CARRIER]
        ,CAST([MODEL] AS NVARCHAR(50)) AS [MODEL]
      ,[MANUFACTURE_YEAR]
      ,CAST(UPPER([AIRCRAFT_STATUS]) AS NVARCHAR(2)) AS [AIRCRAFT_STATUS]
      ,[OPERATING_STATUS]
      ,[NUMBER_OF_SEATS]
--      ,[MANUFACTURER]
      ,[AIRCRAFT_TYPE]
      ,[CAPACITY_IN_POUNDS]
      ,[ACQUISITION_DATE]
--      ,[AIRLINE_ID]
FROM T_F41SCHEDULE_B43
GO

