USE [AirtravelBronze]
GO

CREATE OR ALTER VIEW v_Carriers_Details
AS
SELECT DISTINCT
CAST(CONCAT([AIRLINE_ID],CARRIER,UNIQUE_CARRIER_ENTITY) AS NVARCHAR(20)) AS BK_ID
,CAST([AIRLINE_ID] AS INT) AS [AIRLINE_ID]
,CAST([CARRIER] AS NVARCHAR(3)) AS [CARRIER]
--,[CARRIER_ENTITY]
,CAST([CARRIER_NAME] AS NVARCHAR(200)) AS [CARRIER_NAME]
,CAST([UNIQUE_CARRIER] AS NVARCHAR(10)) AS [UNIQUE_CARRIER]
,CAST([UNIQUE_CARRIER_ENTITY] AS NVARCHAR(10)) AS [UNIQUE_CARRIER_ENTITY]
,CAST([UNIQUE_CARRIER_NAME] AS NVARCHAR(200)) AS [UNIQUE_CARRIER_NAME]
,CAST([WAC] AS INT) AS [WAC]
,CAST([CARRIER_GROUP] AS TINYINT) AS [CARRIER_GROUP]
,CAST([CARRIER_GROUP_NEW] AS TINYINT) AS [CARRIER_GROUP_NEW]
,CAST([REGION] AS NVARCHAR(50)) AS REGION_LONG
,CAST(UPPER(lEFT([REGION],1)) AS NCHAR(1)) AS REGION
,CAST([START_DATE_SOURCE] AS datetime2(7)) AS [START_DATE_SOURCE]
,CAST([THRU_DATE_SOURCE] AS datetime2(7)) AS [THRU_DATE_SOURCE]
FROM
T_CARRIER_DECODE