
---- FARES_DETAILS View Clean ---

USE AirtravelBronze
GO



CREATE OR ALTER VIEW v_FARES_DETAILS AS 
WITH FareCounts AS (
    SELECT
        CONCAT(QUARTER, '-', YEAR, '-', ORIGIN_AIRPORT_SEQ_ID, '-', DEST_AIRPORT_SEQ_ID) AS QYEAR_ORI_DEST,
        MARKET_FARE,
        COUNT(*) AS FareFrequency
    FROM DB1B_MARKET
    GROUP BY
        CONCAT(QUARTER, '-', YEAR, '-', ORIGIN_AIRPORT_SEQ_ID, '-', DEST_AIRPORT_SEQ_ID),
        MARKET_FARE
),
ModeFare AS (
    SELECT
        QYEAR_ORI_DEST,
        MARKET_FARE AS MODE_FARE
    FROM (
        SELECT *,
               ROW_NUMBER() OVER (PARTITION BY QYEAR_ORI_DEST ORDER BY FareFrequency DESC) AS rn
        FROM FareCounts
    ) t
    WHERE rn = 1
)
SELECT
    m.QYEAR_ORI_DEST,
    mf.MODE_FARE,
    CAST(AVG(m.MARKET_DISTANCE) AS INT) AS AVG_MARKET_DISTANCE
FROM (
    SELECT 
        CONCAT(QUARTER, '-', YEAR, '-', ORIGIN_AIRPORT_SEQ_ID, '-', DEST_AIRPORT_SEQ_ID) AS QYEAR_ORI_DEST,
        MARKET_DISTANCE
    FROM DB1B_MARKET
) AS m
INNER JOIN ModeFare mf
    ON m.QYEAR_ORI_DEST = mf.QYEAR_ORI_DEST
GROUP BY m.QYEAR_ORI_DEST, mf.MODE_FARE 