--- Carrier Details Intermeridary table (for DB1) -- 


CREATE OR ALTER   VIEW [dbo].[v_Carriers] AS (
SELECT 
    CAST(AIRLINE_ID AS INT) AS AIRLINE_ID,
    CAST(UNIQUE_CARRIER AS NVARCHAR(50)) AS UNIQUE_CARRIER,
    CAST(UNIQUE_CARRIER_NAME AS NVARCHAR(150)) AS UNIQUE_CARRIER_NAME,
    CAST(WAC AS INT) AS WAC,
    CAST(START_DATE_SOURCE AS datetime2(7)) AS START_DATE_SOURCE
FROM (
    SELECT 
        AIRLINE_ID,
        UNIQUE_CARRIER,
        UNIQUE_CARRIER_NAME,
        WAC,
        START_DATE_SOURCE,
        ROW_NUMBER() OVER (
            PARTITION BY UNIQUE_CARRIER 
            ORDER BY TRY_CAST(START_DATE_SOURCE AS DATE) DESC
        ) AS rn
    FROM T_CARRIER_DECODE
    WHERE UNIQUE_CARRIER IS NOT NULL
) AS ranked
WHERE rn = 1
)
GO


