USE [AirtravelGoldTest]
GO

/****** Object:  Table [dbo].[T100_Master]    Script Date: 06-11-25 14:55:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T100_Master](
	[T100_SK_UNIQUE_ID] [int] NOT NULL,
	[T100_BK_QYEAR_ORI_DEST] [nvarchar](100) NULL,
	[T100_SK_ORIGIN_AIRPORT_SEQ_ID] [int] NULL,
	[T100_SK_DEST_AIRPORT_SEQ_ID] [int] NULL,
	[T100_SK_UNIQUE_CARRIER_ENTITY] [int] NULL,
	[T100_SK_AIRCRAFT_CODE] [int] NULL,
	[T100_AIRCRAFT_GROUP] [int] NULL,
	[T100_DISTANCE_GROUP] [int] NULL,
	[T100_CLASS] [nvarchar](50) NULL,
	[T100_MONTH_YEAR] [int] NULL,
	[T100_DEPARTURES_SCHEDULED] [int] NULL,
	[T100_DEPARTURES_PERFORMED] [int] NULL,
	[T100_DISTANCE] [int] NULL,
	[T100_PAYLOAD] [int] NULL,
	[T100_SEATS] [int] NULL,
	[T100_PASSENGERS] [int] NULL,
	[T100_FREIGHT] [int] NULL,
	[T100_MAIL] [int] NULL,
	[T100_RAMP_TO_RAMP] [int] NULL,
	[T100_AIR_TIME] [int] NULL,
	[T100_AIRCRAFT_CONFIG] [int] NULL,
	[T100_DATA_SOURCE] [nvarchar](250) NULL,
	[Aorig_AIRPORT_SEQ_ID] [int] NULL,
	[Aorig_AIRPORT_ID] [int] NULL,
	[Aorig_AIRPORT] [nvarchar](3) NULL,
	[Aorig_DISPLAY_AIRPORT_NAME] [nvarchar](100) NULL,
	[Aorig_DISPLAY_AIRPORT_CITY_NAME_FULL] [nvarchar](100) NULL,
	[Aorig_AIRPORT_WAC] [int] NULL,
	[Aorig_AIRPORT_COUNTRY_NAME] [nvarchar](200) NULL,
	[Aorig_AIRPORT_COUNTRY_CODE_ISO] [nvarchar](10) NULL,
	[Aorig_AIRPORT_STATE_NAME] [nvarchar](200) NULL,
	[Aorig_AIRPORT_STATE_CODE] [nvarchar](10) NULL,
	[Aorig_AIRPORT_STATE_FIPS] [int] NULL,
	[Aorig_CITY_MARKET_ID] [int] NULL,
	[Aorig_DISPLAY_CITY_MARKET_NAME_FULL] [nvarchar](100) NULL,
	[Aorig_CITY_MARKET_WAC] [int] NULL,
	[Aorig_LAT_DEGREES] [int] NULL,
	[Aorig_LAT_HEMISPHERE] [nchar](1) NULL,
	[Aorig_LAT_MINUTES] [int] NULL,
	[Aorig_LAT_SECONDS] [int] NULL,
	[Aorig_LATITUTE] [decimal](9, 6) NULL,
	[Aorig_LON_DEGREES] [int] NULL,
	[Aorig_LON_HEMISPHERE] [nchar](1) NULL,
	[Aorig_LON_MINUTES] [int] NULL,
	[Aorig_LON_SECONDS] [int] NULL,
	[Aorig_LONGITUDE] [decimal](9, 6) NULL,
	[Aorig_AIRPORT_START_DATE] [datetime2](7) NULL,
	[Aorig_AIRPORT_THRU_DATE] [datetime2](7) NULL,
	[Aorig_AIRPORT_IS_CLOSED] [bit] NULL,
	[Aorig_AIRPORT_IS_LATEST] [bit] NULL,
	[Adest_AIRPORT_SEQ_ID] [int] NULL,
	[Adest_AIRPORT_ID] [int] NULL,
	[Adest_AIRPORT] [nvarchar](3) NULL,
	[Adest_DISPLAY_AIRPORT_NAME] [nvarchar](100) NULL,
	[Adest_DISPLAY_AIRPORT_CITY_NAME_FULL] [nvarchar](100) NULL,
	[Adest_AIRPORT_WAC] [int] NULL,
	[Adest_AIRPORT_COUNTRY_NAME] [nvarchar](200) NULL,
	[Adest_AIRPORT_COUNTRY_CODE_ISO] [nvarchar](10) NULL,
	[Adest_AIRPORT_STATE_NAME] [nvarchar](200) NULL,
	[Adest_AIRPORT_STATE_CODE] [nvarchar](10) NULL,
	[Adest_AIRPORT_STATE_FIPS] [int] NULL,
	[Adest_CITY_MARKET_ID] [int] NULL,
	[Adest_DISPLAY_CITY_MARKET_NAME_FULL] [nvarchar](100) NULL,
	[Adest_CITY_MARKET_WAC] [int] NULL,
	[Adest_LAT_DEGREES] [int] NULL,
	[Adest_LAT_HEMISPHERE] [nchar](1) NULL,
	[Adest_LAT_MINUTES] [int] NULL,
	[Adest_LAT_SECONDS] [int] NULL,
	[Adest_LATITUTE] [decimal](9, 6) NULL,
	[Adest_LON_DEGREES] [int] NULL,
	[Adest_LON_HEMISPHERE] [nchar](1) NULL,
	[Adest_LON_MINUTES] [int] NULL,
	[Adest_LON_SECONDS] [int] NULL,
	[Adest_LONGITUDE] [decimal](9, 6) NULL,
	[Adest_AIRPORT_START_DATE] [datetime2](7) NULL,
	[Adest_AIRPORT_THRU_DATE] [datetime2](7) NULL,
	[Adest_AIRPORT_IS_CLOSED] [bit] NULL,
	[Adest_AIRPORT_IS_LATEST] [bit] NULL,
	[CarriersDetails_SK_ID] [int] NULL,
	[CarriersDetails_BK_ID] [nvarchar](20) NULL,
	[CarriersDetails_AIRLINE_ID] [int] NULL,
	[CarriersDetails_CARRIER] [nvarchar](3) NULL,
	[CarriersDetails_CARRIER_NAME] [nvarchar](200) NULL,
	[CarriersDetails_UNIQUE_CARRIER] [nvarchar](10) NULL,
	[CarriersDetails_UNIQUE_CARRIER_ENTITY] [nvarchar](10) NULL,
	[CarriersDetails_UNIQUE_CARRIER_NAME] [nvarchar](200) NULL,
	[CarriersDetails_WAC] [int] NULL,
	[CarriersDetails_CARRIER_GROUP] [tinyint] NULL,
	[CarriersDetails_CARRIER_GROUP_NEW] [tinyint] NULL,
	[CarriersDetails_REGION_LONG] [nvarchar](50) NULL,
	[CarriersDetails_REGION] [nchar](1) NULL,
	[CarriersDetails_START_DATE_SOURCE] [datetime2](7) NULL,
	[CarriersDetails_THRU_DATE_SOURCE] [datetime2](7) NULL,
	[CarriersDetails_FK_CARRIER_ID] [int] NULL,
	[Aircrafttypelookup_SK_ID] [int] NULL,
	[Aircrafttypelookup_AIRCRAFT_TYPE] [int] NULL,
	[Aircrafttypelookup_DESCRIPTION] [nvarchar](200) NULL,
	[Fares_Details_BK_QYEAR_ORI_DEST] [nvarchar](100) NULL,
	[Fares_Details_MODE_FARE] [float] NULL,
	[Fares_Details_AVG_MARKET_DISTANCE] [float] NULL,
	[Distance_Group_BK_Code] [int] NULL,
	[Distance_Group_DESCRIPTION] [nvarchar](255) NULL,
	[Service_Class_BK_Code] [nvarchar](3) NULL,
	[Service_Class_DESCRIPTION] [nvarchar](255) NULL,
	[Aircraft_Group_BK_Code] [int] NULL,
	[Aircraft_Group_DESCRIPTION] [nvarchar](255) NULL,
	[AVG_PASSENGERS_FLIGHT] [float] NULL,
	[T100_PASSENGERS_LOADFACTOR_PCT] [nvarchar](4000) NULL
) ON [PRIMARY]
GO


