USE [AirtravelGoldTest]
GO

/****** Object:  Table [dbo].[DB1_Master]    Script Date: 06-11-25 14:54:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DB1_Master](
	[DB1_SK_UNIQUE_ID] [int] NOT NULL,
	[DB1_BK_QYEAR_ORI_DEST] [nvarchar](100) NOT NULL,
	[DB1_SK_ORIGIN_AIRPORT_SEQ_ID] [int] NULL,
	[DB1_SK_DEST_AIRPORT_SEQ_ID] [int] NULL,
	[DB1_SK_UNIQUE_CARRIER_ID] [int] NULL,
	[DB1_MKT_ID] [bigint] NOT NULL,
	[DB1_QUARTER_YEAR] [int] NOT NULL,
	[DB1_MARKET_FARE] [float] NULL,
	[DB1_MARKET_DISTANCE] [int] NULL,
	[CA_SK_UNIQUE_ID] [int] NULL,
	[CA_BK_UNIQUE_CARRIER] [nvarchar](50) NULL,
	[CA_AIRLINE_ID] [int] NULL,
	[CA_UNIQUE_CARRIER_NAME] [nvarchar](150) NULL,
	[CA_WAC] [int] NULL,
	[CA_START_DATE_SOURCE] [datetime2](7) NULL,
	[Aorig_AIRPORT_SEQ_ID] [int] NULL,
	[Aorig_AIRPORT_ID] [int] NULL,
	[Aorig_AIRPORT] [nvarchar](3) NULL,
	[Aorig_DISPLAY_AIRPORT_NAME] [nvarchar](100) NULL,
	[Aorig_DISPLAY_AIRPORT_CITY_NAME_FULL] [nvarchar](100) NULL,
	[Aorig_AIRPORT_WAC] [int] NULL,
	[Aorig_AIRPORT_COUNTRY_NAME] [nvarchar](200) NULL,
	[Aorig_AIRPORT_COUNTRY_CODE_ISO] [nvarchar](10) NULL,
	[Aorig_AIRPORT_STATE_NAME] [nvarchar](200) NULL,
	[Aorig_AIRPORT_STATE_CODE] [nvarchar](10) NULL,
	[Aorig_AIRPORT_STATE_FIPS] [int] NULL,
	[Aorig_CITY_MARKET_ID] [int] NULL,
	[Aorig_DISPLAY_CITY_MARKET_NAME_FULL] [nvarchar](100) NULL,
	[Aorig_CITY_MARKET_WAC] [int] NULL,
	[Aorig_LAT_DEGREES] [int] NULL,
	[Aorig_LAT_HEMISPHERE] [nchar](1) NULL,
	[Aorig_LAT_MINUTES] [int] NULL,
	[Aorig_LAT_SECONDS] [int] NULL,
	[Aorig_LATITUTE] [decimal](9, 6) NULL,
	[Aorig_LON_DEGREES] [int] NULL,
	[Aorig_LON_HEMISPHERE] [nchar](1) NULL,
	[Aorig_LON_MINUTES] [int] NULL,
	[Aorig_LON_SECONDS] [int] NULL,
	[Aorig_LONGITUDE] [decimal](9, 6) NULL,
	[Aorig_AIRPORT_START_DATE] [datetime2](7) NULL,
	[Aorig_AIRPORT_THRU_DATE] [datetime2](7) NULL,
	[Aorig_AIRPORT_IS_CLOSED] [bit] NULL,
	[Aorig_AIRPORT_IS_LATEST] [bit] NULL,
	[Adest_AIRPORT_SEQ_ID] [int] NULL,
	[Adest_AIRPORT_ID] [int] NULL,
	[Adest_AIRPORT] [nvarchar](3) NULL,
	[Adest_DISPLAY_AIRPORT_NAME] [nvarchar](100) NULL,
	[Adest_DISPLAY_AIRPORT_CITY_NAME_FULL] [nvarchar](100) NULL,
	[Adest_AIRPORT_WAC] [int] NULL,
	[Adest_AIRPORT_COUNTRY_NAME] [nvarchar](200) NULL,
	[Adest_AIRPORT_COUNTRY_CODE_ISO] [nvarchar](10) NULL,
	[Adest_AIRPORT_STATE_NAME] [nvarchar](200) NULL,
	[Adest_AIRPORT_STATE_CODE] [nvarchar](10) NULL,
	[Adest_AIRPORT_STATE_FIPS] [int] NULL,
	[Adest_CITY_MARKET_ID] [int] NULL,
	[Adest_DISPLAY_CITY_MARKET_NAME_FULL] [nvarchar](100) NULL,
	[Adest_CITY_MARKET_WAC] [int] NULL,
	[Adest_LAT_DEGREES] [int] NULL,
	[Adest_LAT_HEMISPHERE] [nchar](1) NULL,
	[Adest_LAT_MINUTES] [int] NULL,
	[Adest_LAT_SECONDS] [int] NULL,
	[Adest_LATITUTE] [decimal](9, 6) NULL,
	[Adest_LON_DEGREES] [int] NULL,
	[Adest_LON_HEMISPHERE] [nchar](1) NULL,
	[Adest_LON_MINUTES] [int] NULL,
	[Adest_LON_SECONDS] [int] NULL,
	[Adest_LONGITUDE] [decimal](9, 6) NULL,
	[Adest_AIRPORT_START_DATE] [datetime2](7) NULL,
	[Adest_AIRPORT_THRU_DATE] [datetime2](7) NULL,
	[Adest_AIRPORT_IS_CLOSED] [bit] NULL,
	[Adest_AIRPORT_IS_LATEST] [bit] NULL,
	[Fares_Details_BK_QYEAR_ORI_DEST] [nvarchar](100) NULL,
	[Fares_Details_MODE_FARE] [float] NULL,
	[Fares_Details_AVG_MARKET_DISTANCE] [float] NULL
) ON [PRIMARY]
GO


