USE [AirtravelSilver]
GO

CREATE TABLE FARES_DETAILS(
      BK_QYEAR_ORI_DEST NVARCHAR(50) CONSTRAINT BK_QYEAR_ORI_DEST_FARES_DETAILS PRIMARY KEY
    , MODE_FARE INT 
    , AVG_MARKET_DISTANCE INT );


