USE [AirtravelSilver]
GO

/****** Object:  View [dbo].[DB1_MasterTable_Gold]    Script Date: 06-11-25 12:59:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER   VIEW [dbo].[DB1_MasterTable_Gold]
AS
SELECT 
       DB1.[SK_UNIQUE_ID] AS DB1_SK_UNIQUE_ID
      ,DB1.[BK_QYEAR_ORI_DEST] AS DB1_BK_QYEAR_ORI_DEST
      ,DB1.[SK_ORIGIN_AIRPORT_SEQ_ID] AS DB1_SK_ORIGIN_AIRPORT_SEQ_ID
      ,DB1.[SK_DEST_AIRPORT_SEQ_ID] AS DB1_SK_DEST_AIRPORT_SEQ_ID
      ,DB1.[SK_UNIQUE_CARRIER_ID] AS DB1_SK_UNIQUE_CARRIER_ID
      ,DB1.[MKT_ID] AS DB1_MKT_ID
      ,DB1.[QUARTER_YEAR] AS DB1_QUARTER_YEAR
      ,DB1.[MARKET_FARE] AS DB1_MARKET_FARE
      ,DB1.[MARKET_DISTANCE] AS DB1_MARKET_DISTANCE
-- Carrier
      ,CA.[SK_UNIQUE_ID] AS CA_SK_UNIQUE_ID
      ,CA.[BK_UNIQUE_CARRIER] AS CA_BK_UNIQUE_CARRIER
      ,CA.[AIRLINE_ID] AS CA_AIRLINE_ID
      ,CA.[UNIQUE_CARRIER_NAME] AS CA_UNIQUE_CARRIER_NAME
      ,CA.[WAC] AS CA_WAC
      ,CA.[START_DATE_SOURCE] AS CA_START_DATE_SOURCE
-- Airports origin
    , Aorig.[AIRPORT_SEQ_ID] AS Aorig_AIRPORT_SEQ_ID
    , Aorig.[AIRPORT_ID] AS Aorig_AIRPORT_ID
    , Aorig.[AIRPORT] AS Aorig_AIRPORT
    , Aorig.[DISPLAY_AIRPORT_NAME] AS Aorig_DISPLAY_AIRPORT_NAME
    , Aorig.[DISPLAY_AIRPORT_CITY_NAME_FULL] AS Aorig_DISPLAY_AIRPORT_CITY_NAME_FULL
    , Aorig.[AIRPORT_WAC] AS Aorig_AIRPORT_WAC
    , Aorig.[AIRPORT_COUNTRY_NAME] AS Aorig_AIRPORT_COUNTRY_NAME
    , Aorig.[AIRPORT_COUNTRY_CODE_ISO] AS Aorig_AIRPORT_COUNTRY_CODE_ISO
    , Aorig.[AIRPORT_STATE_NAME] AS Aorig_AIRPORT_STATE_NAME
    , Aorig.[AIRPORT_STATE_CODE] AS Aorig_AIRPORT_STATE_CODE
    , Aorig.[AIRPORT_STATE_FIPS] AS Aorig_AIRPORT_STATE_FIPS
    , Aorig.[CITY_MARKET_ID] AS Aorig_CITY_MARKET_ID
    , Aorig.[DISPLAY_CITY_MARKET_NAME_FULL] AS Aorig_DISPLAY_CITY_MARKET_NAME_FULL
    , Aorig.[CITY_MARKET_WAC] AS Aorig_CITY_MARKET_WAC
    , Aorig.[LAT_DEGREES] AS Aorig_LAT_DEGREES
    , Aorig.[LAT_HEMISPHERE] AS Aorig_LAT_HEMISPHERE
    , Aorig.[LAT_MINUTES] AS Aorig_LAT_MINUTES
    , Aorig.[LAT_SECONDS] AS Aorig_LAT_SECONDS
    , Aorig.[LATITUTE] AS Aorig_LATITUTE
    , Aorig.[LON_DEGREES] AS Aorig_LON_DEGREES
    , Aorig.[LON_HEMISPHERE] AS Aorig_LON_HEMISPHERE
    , Aorig.[LON_MINUTES] AS Aorig_LON_MINUTES
    , Aorig.[LON_SECONDS] AS Aorig_LON_SECONDS
    , Aorig.[LONGITUDE] AS Aorig_LONGITUDE
    , Aorig.[AIRPORT_START_DATE] AS Aorig_AIRPORT_START_DATE
    , Aorig.[AIRPORT_THRU_DATE] AS Aorig_AIRPORT_THRU_DATE
    , Aorig.[AIRPORT_IS_CLOSED] AS Aorig_AIRPORT_IS_CLOSED
    , Aorig.[AIRPORT_IS_LATEST] AS Aorig_AIRPORT_IS_LATEST
-- Airports destination
    , Adest.[AIRPORT_SEQ_ID] AS Adest_AIRPORT_SEQ_ID
    , Adest.[AIRPORT_ID] AS Adest_AIRPORT_ID
    , Adest.[AIRPORT] AS Adest_AIRPORT
    , Adest.[DISPLAY_AIRPORT_NAME] AS Adest_DISPLAY_AIRPORT_NAME
    , Adest.[DISPLAY_AIRPORT_CITY_NAME_FULL] AS Adest_DISPLAY_AIRPORT_CITY_NAME_FULL
    , Adest.[AIRPORT_WAC] AS Adest_AIRPORT_WAC
    , Adest.[AIRPORT_COUNTRY_NAME] AS Adest_AIRPORT_COUNTRY_NAME
    , Adest.[AIRPORT_COUNTRY_CODE_ISO] AS Adest_AIRPORT_COUNTRY_CODE_ISO
    , Adest.[AIRPORT_STATE_NAME] AS Adest_AIRPORT_STATE_NAME
    , Adest.[AIRPORT_STATE_CODE] AS Adest_AIRPORT_STATE_CODE
    , Adest.[AIRPORT_STATE_FIPS] AS Adest_AIRPORT_STATE_FIPS
    , Adest.[CITY_MARKET_ID] AS Adest_CITY_MARKET_ID
    , Adest.[DISPLAY_CITY_MARKET_NAME_FULL] AS Adest_DISPLAY_CITY_MARKET_NAME_FULL
    , Adest.[CITY_MARKET_WAC] AS Adest_CITY_MARKET_WAC
    , Adest.[LAT_DEGREES] AS Adest_LAT_DEGREES
    , Adest.[LAT_HEMISPHERE] AS Adest_LAT_HEMISPHERE
    , Adest.[LAT_MINUTES] AS Adest_LAT_MINUTES
    , Adest.[LAT_SECONDS] AS Adest_LAT_SECONDS
    , Adest.[LATITUTE] AS Adest_LATITUTE
    , Adest.[LON_DEGREES] AS Adest_LON_DEGREES
    , Adest.[LON_HEMISPHERE] AS Adest_LON_HEMISPHERE
    , Adest.[LON_MINUTES] AS Adest_LON_MINUTES
    , Adest.[LON_SECONDS] AS Adest_LON_SECONDS
    , Adest.[LONGITUDE] AS Adest_LONGITUDE
    , Adest.[AIRPORT_START_DATE] AS Adest_AIRPORT_START_DATE
    , Adest.[AIRPORT_THRU_DATE] AS Adest_AIRPORT_THRU_DATE
    , Adest.[AIRPORT_IS_CLOSED] AS Adest_AIRPORT_IS_CLOSED
    , Adest.[AIRPORT_IS_LATEST] AS Adest_AIRPORT_IS_LATEST
    -- FARES_DETAILS
    , FD.[BK_QYEAR_ORI_DEST] AS Fares_Details_BK_QYEAR_ORI_DEST
    , FD.[MODE_FARE] AS Fares_Details_MODE_FARE
    , FD.[AVG_MARKET_DISTANCE] AS Fares_Details_AVG_MARKET_DISTANCE
FROM Fact_DB1 DB1
LEFT JOIN FARES_DETAILS FD ON DB1.BK_QYEAR_ORI_DEST = FD.BK_QYEAR_ORI_DEST
LEFT JOIN Carriers CA ON CA.SK_UNIQUE_ID = DB1.SK_UNIQUE_CARRIER_ID
LEFT JOIN Airports Aorig ON Aorig.AIRPORT_SEQ_ID = DB1.SK_ORIGIN_AIRPORT_SEQ_ID
LEFT JOIN Airports Adest ON Adest.AIRPORT_SEQ_ID = DB1.SK_DEST_AIRPORT_SEQ_ID
GO


