USE [AirtravelSilverTest]
GO

/****** Object:  Table [dbo].[Fact_DB1]    Script Date: 31-10-25 15:11:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Fact_DB1](
	[SK_UNIQUE_ID] [int] IDENTITY(1,1) NOT NULL,
	[BK_QYEAR_ORI_DEST] [nvarchar](100) NOT NULL,
	[SK_ORIGIN_AIRPORT_SEQ_ID] [int] NULL,
	[SK_DEST_AIRPORT_SEQ_ID] [int] NULL,
	[SK_UNIQUE_CARRIER_ID] [int] NULL,
	[MKT_ID] [bigint] NOT NULL,
	[QUARTER_YEAR] [int] NOT NULL,
	[MARKET_FARE] [float] NULL,
	[MARKET_DISTANCE] [int] NULL,
 CONSTRAINT [PK_UNIQUE_ID_DB1] PRIMARY KEY CLUSTERED 
(
	[SK_UNIQUE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Fact_DB1]  WITH CHECK ADD  CONSTRAINT [FK_DEST_AIRPORT_SEQ_ID_DB1] FOREIGN KEY([SK_DEST_AIRPORT_SEQ_ID])
REFERENCES [dbo].[Airports] ([AIRPORT_SEQ_ID])
GO

ALTER TABLE [dbo].[Fact_DB1] CHECK CONSTRAINT [FK_DEST_AIRPORT_SEQ_ID_DB1]
GO

ALTER TABLE [dbo].[Fact_DB1]  WITH CHECK ADD  CONSTRAINT [FK_ORIGIN_AIRPORT_SEQ_ID_DB1] FOREIGN KEY([SK_ORIGIN_AIRPORT_SEQ_ID])
REFERENCES [dbo].[Airports] ([AIRPORT_SEQ_ID])
GO

ALTER TABLE [dbo].[Fact_DB1] CHECK CONSTRAINT [FK_ORIGIN_AIRPORT_SEQ_ID_DB1]
GO

ALTER TABLE [dbo].[Fact_DB1]  WITH CHECK ADD  CONSTRAINT [FK_UNIQUE_CARRIER_DB1] FOREIGN KEY([SK_UNIQUE_CARRIER_ID])
REFERENCES [dbo].[Carriers] ([SK_UNIQUE_ID])
GO

ALTER TABLE [dbo].[Fact_DB1] CHECK CONSTRAINT [FK_UNIQUE_CARRIER_DB1]
GO

