USE [AirtravelSilverTest]
GO

/****** Object:  Table [dbo].[Aircrafts_Type_Lookup]    Script Date: 28-10-25 11:06:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Aircrafts_Type_Lookup](
	[AIRCRAFT_TYPE] [int] NOT NULL,
	[DESCRIPTION] [nvarchar](200) NOT NULL,
 CONSTRAINT [PK_Aircrafts_Type_Lookup] PRIMARY KEY CLUSTERED 
(
	[AIRCRAFT_TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


