USE [AirtravelSilverTest]
GO

/****** Object:  Table [dbo].[Carriers]    Script Date: 31-10-25 14:37:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Carriers](
	[SK_UNIQUE_ID] [int] IDENTITY(1,1) NOT NULL,
	[BK_UNIQUE_CARRIER] [nvarchar](50) NULL,
	[AIRLINE_ID] [int] NULL,
	[UNIQUE_CARRIER_NAME] [nvarchar](150) NULL,
	[WAC] [int] NULL,
	[START_DATE_SOURCE] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_UNIQUE_ID_Carriers_DIM] PRIMARY KEY CLUSTERED 
(
	[SK_UNIQUE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ__Carriers__C817614D31BB4FB6] UNIQUE NONCLUSTERED 
(
	[BK_UNIQUE_CARRIER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

