USE [AirtravelSilverTest]
GO

/****** Object:  Table [dbo].[Aircrafts_type]    Script Date: 28-10-25 14:29:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Aircrafts_type](
	[AIRCRAFT_TYPE] [int] NOT NULL,
	[AIRCRAFT_TYPE_LOOKUP] [int] NOT NULL,
	[MANUFACTURER] [nvarchar](200) NOT NULL,
 CONSTRAINT [PK_Aircrafts_type] PRIMARY KEY CLUSTERED 
(
	[AIRCRAFT_TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO



USE [AirtravelSilverTest]
GO

/****** Object:  Table [dbo].[Aircrafts]    Script Date: 28-10-25 14:28:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Aircrafts](
	[BK_ID] [nvarchar](50) NOT NULL,
	[SERIAL_NUMBER] [nvarchar](40) NOT NULL,
	[TAIL_NUMBER] [nvarchar](10) NOT NULL,
	[UNIQUE_CARRIER] [nvarchar](5) NOT NULL,
	[MODEL] [nvarchar](50) NOT NULL,
	[MANUFACTURE_YEAR] [int] NOT NULL,
	[AIRCRAFT_STATUS] [nvarchar](2) NOT NULL,
	[OPERATING_STATUS] [bit] NOT NULL,
	[NUMBER_OF_SEATS] [int] NOT NULL,
	[AIRCRAFT_TYPE] [int] NOT NULL,
	[CAPACITY_IN_POUNDS] [int] NOT NULL,
	[ACQUISITION_DATE] [datetime2](7) NULL,
 CONSTRAINT [PK_Aircrafts] PRIMARY KEY CLUSTERED 
(
	[BK_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Aircrafts]  WITH CHECK ADD  CONSTRAINT [FK_Aircrafts_Aircrafts_type] FOREIGN KEY([AIRCRAFT_TYPE])
REFERENCES [dbo].[Aircrafts_type] ([AIRCRAFT_TYPE])
GO

ALTER TABLE [dbo].[Aircrafts] CHECK CONSTRAINT [FK_Aircrafts_Aircrafts_type]
GO

