USE [AirtravelSilverTest]
GO

CREATE TABLE Fact_T100(
      SK_UNIQUE_ID INT IDENTITY(1, 1) CONSTRAINT PK_UNQIUE_ID_T100 PRIMARY KEY
    , BK_QYEAR_ORI_DEST INT 
    , SK_ORIGIN_AIRPORT_SEQ_ID INT CONSTRAINT FK_ORIGIN_AIRPORT_SEQ_ID_T100 REFERENCES Airport_details_DIM(SK_AIRPORT_SEQ_ID)
    , SK_DEST_AIRPORT_SEQ_ID INT CONSTRAINT FK_DEST_AIRPORT_SEQ_ID_T100 REFERENCES Airport_details_DIM (SK_AIRPORT_SEQ_ID)
    , SK_UNIQUE_CARRIER_ENTITY NVARCHAR(150) CONSTRAINT FK_UNIQUE_CARRIER_ENTITY_T100 REFERENCES Carrier_details_DIM (SK_UNIQUE_CARRIER_ENTITY)
    , SK_AIRCRAFT_CODE INT CONSTRAINT FK_AIRCRAFT_CODE_T100 REFERENCES Aircraft_Type_DIM (SK_AIRCRAFT_CODE)
    , AIRCRAFT_GROUP INT 
    , DISTANCE_GROUP INT 
    , CLASS NVARCHAR(50)
    , MONTH_YEAR INT
    , DEPARTURES_SCHEDULED INT
    , DEPARTURES_PERFORMED INT
    , DISTANCE INT
    , PAYLOAD INT
    , SEATS INT
    , PASSENGERS INT
    , FREIGHT INT
    , MAIL INT
    , RAMP_TO_RAMP INT
    , AIR_TIME INT
    , AIRCRAFT_CONFIG INT
    , [DATA_SOURCE] NVARCHAR(250)


    --- Index creation -- 

    CREATE NONCLUSTERED INDEX IX_Fact_T100_QYEAR_CARRIER_MONTH_AIRCRAFT_CLASS_CONFIG
ON dbo.Fact_T100 (
      BK_QYEAR_ORI_DEST,
      SK_UNIQUE_CARRIER_ENTITY,
      MONTH_YEAR,
      SK_AIRCRAFT_CODE,
      CLASS,
      AIRCRAFT_CONFIG
);
GO