USE [AirtravelSilver]
GO


CREATE TABLE [dbo].[Fact_DB1_Stagging](
	[SK_UNIQUE_ID] [int] IDENTITY(1,1) NOT NULL,
	[BK_QYEAR_ORI_DEST] [nvarchar](50) NOT NULL,
	[SK_ORIGIN_AIRPORT_SEQ_ID] [int] NULL,
	[SK_DEST_AIRPORT_SEQ_ID] [int] NULL,
	[SK_UNIQUE_CARRIER_ID] [int] NULL,
	[MKT_ID] [bigint] NOT NULL,
	[QUARTER_YEAR] [int] NOT NULL,
	[MARKET_FARE] [float] NULL,
	[MARKET_DISTANCE] [int] NULL,
 CONSTRAINT [PK_UNIQUE_ID_DB1_Stagging] PRIMARY KEY CLUSTERED 
(
	[SK_UNIQUE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


