USE [AirtravelSilver]
GO

/****** Object:  View [dbo].[T100_MasterTable_Gold]    Script Date: 06-11-25 13:00:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE OR ALTER   VIEW [dbo].[T100_MasterTable_Gold]
AS
SELECT
--  T100
      T100.[SK_UNIQUE_ID] AS T100_SK_UNIQUE_ID
    , T100.[BK_QYEAR_ORI_DEST] AS T100_BK_QYEAR_ORI_DEST
    , T100.[SK_ORIGIN_AIRPORT_SEQ_ID] AS T100_SK_ORIGIN_AIRPORT_SEQ_ID
    , T100.[SK_DEST_AIRPORT_SEQ_ID] AS T100_SK_DEST_AIRPORT_SEQ_ID
    , T100.[SK_UNIQUE_CARRIER_ENTITY] AS T100_SK_UNIQUE_CARRIER_ENTITY
    , T100.[SK_AIRCRAFT_CODE] AS T100_SK_AIRCRAFT_CODE
    , T100.[AIRCRAFT_GROUP] AS T100_AIRCRAFT_GROUP
    , T100.[DISTANCE_GROUP] AS T100_DISTANCE_GROUP
    , T100.[CLASS] AS T100_CLASS
    , T100.[MONTH_YEAR] AS T100_MONTH_YEAR
    , T100.[DEPARTURES_SCHEDULED] AS T100_DEPARTURES_SCHEDULED
    , T100.[DEPARTURES_PERFORMED] AS T100_DEPARTURES_PERFORMED
    , T100.[DISTANCE] AS T100_DISTANCE
    , T100.[PAYLOAD] AS T100_PAYLOAD
    , T100.[SEATS] AS T100_SEATS
    , T100.[PASSENGERS] AS T100_PASSENGERS
    , T100.[FREIGHT] AS T100_FREIGHT
    , T100.[MAIL] AS T100_MAIL
    , T100.[RAMP_TO_RAMP] AS T100_RAMP_TO_RAMP
    , T100.[AIR_TIME] AS T100_AIR_TIME
    , T100.[AIRCRAFT_CONFIG] AS T100_AIRCRAFT_CONFIG
    , T100.[DATA_SOURCE] AS T100_DATA_SOURCE
-- Airports origin
    , Aorig.[AIRPORT_SEQ_ID] AS Aorig_AIRPORT_SEQ_ID
    , Aorig.[AIRPORT_ID] AS Aorig_AIRPORT_ID
    , Aorig.[AIRPORT] AS Aorig_AIRPORT
    , Aorig.[DISPLAY_AIRPORT_NAME] AS Aorig_DISPLAY_AIRPORT_NAME
    , Aorig.[DISPLAY_AIRPORT_CITY_NAME_FULL] AS Aorig_DISPLAY_AIRPORT_CITY_NAME_FULL
    , Aorig.[AIRPORT_WAC] AS Aorig_AIRPORT_WAC
    , Aorig.[AIRPORT_COUNTRY_NAME] AS Aorig_AIRPORT_COUNTRY_NAME
    , Aorig.[AIRPORT_COUNTRY_CODE_ISO] AS Aorig_AIRPORT_COUNTRY_CODE_ISO
    , Aorig.[AIRPORT_STATE_NAME] AS Aorig_AIRPORT_STATE_NAME
    , Aorig.[AIRPORT_STATE_CODE] AS Aorig_AIRPORT_STATE_CODE
    , Aorig.[AIRPORT_STATE_FIPS] AS Aorig_AIRPORT_STATE_FIPS
    , Aorig.[CITY_MARKET_ID] AS Aorig_CITY_MARKET_ID
    , Aorig.[DISPLAY_CITY_MARKET_NAME_FULL] AS Aorig_DISPLAY_CITY_MARKET_NAME_FULL
    , Aorig.[CITY_MARKET_WAC] AS Aorig_CITY_MARKET_WAC
    , Aorig.[LAT_DEGREES] AS Aorig_LAT_DEGREES
    , Aorig.[LAT_HEMISPHERE] AS Aorig_LAT_HEMISPHERE
    , Aorig.[LAT_MINUTES] AS Aorig_LAT_MINUTES
    , Aorig.[LAT_SECONDS] AS Aorig_LAT_SECONDS
    , Aorig.[LATITUTE] AS Aorig_LATITUTE
    , Aorig.[LON_DEGREES] AS Aorig_LON_DEGREES
    , Aorig.[LON_HEMISPHERE] AS Aorig_LON_HEMISPHERE
    , Aorig.[LON_MINUTES] AS Aorig_LON_MINUTES
    , Aorig.[LON_SECONDS] AS Aorig_LON_SECONDS
    , Aorig.[LONGITUDE] AS Aorig_LONGITUDE
    , Aorig.[AIRPORT_START_DATE] AS Aorig_AIRPORT_START_DATE
    , Aorig.[AIRPORT_THRU_DATE] AS Aorig_AIRPORT_THRU_DATE
    , Aorig.[AIRPORT_IS_CLOSED] AS Aorig_AIRPORT_IS_CLOSED
    , Aorig.[AIRPORT_IS_LATEST] AS Aorig_AIRPORT_IS_LATEST
-- Airports destination
    , Adest.[AIRPORT_SEQ_ID] AS Adest_AIRPORT_SEQ_ID
    , Adest.[AIRPORT_ID] AS Adest_AIRPORT_ID
    , Adest.[AIRPORT] AS Adest_AIRPORT
    , Adest.[DISPLAY_AIRPORT_NAME] AS Adest_DISPLAY_AIRPORT_NAME
    , Adest.[DISPLAY_AIRPORT_CITY_NAME_FULL] AS Adest_DISPLAY_AIRPORT_CITY_NAME_FULL
    , Adest.[AIRPORT_WAC] AS Adest_AIRPORT_WAC
    , Adest.[AIRPORT_COUNTRY_NAME] AS Adest_AIRPORT_COUNTRY_NAME
    , Adest.[AIRPORT_COUNTRY_CODE_ISO] AS Adest_AIRPORT_COUNTRY_CODE_ISO
    , Adest.[AIRPORT_STATE_NAME] AS Adest_AIRPORT_STATE_NAME
    , Adest.[AIRPORT_STATE_CODE] AS Adest_AIRPORT_STATE_CODE
    , Adest.[AIRPORT_STATE_FIPS] AS Adest_AIRPORT_STATE_FIPS
    , Adest.[CITY_MARKET_ID] AS Adest_CITY_MARKET_ID
    , Adest.[DISPLAY_CITY_MARKET_NAME_FULL] AS Adest_DISPLAY_CITY_MARKET_NAME_FULL
    , Adest.[CITY_MARKET_WAC] AS Adest_CITY_MARKET_WAC
    , Adest.[LAT_DEGREES] AS Adest_LAT_DEGREES
    , Adest.[LAT_HEMISPHERE] AS Adest_LAT_HEMISPHERE
    , Adest.[LAT_MINUTES] AS Adest_LAT_MINUTES
    , Adest.[LAT_SECONDS] AS Adest_LAT_SECONDS
    , Adest.[LATITUTE] AS Adest_LATITUTE
    , Adest.[LON_DEGREES] AS Adest_LON_DEGREES
    , Adest.[LON_HEMISPHERE] AS Adest_LON_HEMISPHERE
    , Adest.[LON_MINUTES] AS Adest_LON_MINUTES
    , Adest.[LON_SECONDS] AS Adest_LON_SECONDS
    , Adest.[LONGITUDE] AS Adest_LONGITUDE
    , Adest.[AIRPORT_START_DATE] AS Adest_AIRPORT_START_DATE
    , Adest.[AIRPORT_THRU_DATE] AS Adest_AIRPORT_THRU_DATE
    , Adest.[AIRPORT_IS_CLOSED] AS Adest_AIRPORT_IS_CLOSED
    , Adest.[AIRPORT_IS_LATEST] AS Adest_AIRPORT_IS_LATEST
-- Carriers_Details
    , CD.[SK_ID] AS CarriersDetails_SK_ID
    , CD.[BK_ID] AS CarriersDetails_BK_ID
    , CD.[AIRLINE_ID] AS CarriersDetails_AIRLINE_ID
    , CD.[CARRIER] AS CarriersDetails_CARRIER
    , CD.[CARRIER_NAME] AS CarriersDetails_CARRIER_NAME
    , CD.[UNIQUE_CARRIER] AS CarriersDetails_UNIQUE_CARRIER
    , CD.[UNIQUE_CARRIER_ENTITY] AS CarriersDetails_UNIQUE_CARRIER_ENTITY
    , CD.[UNIQUE_CARRIER_NAME] AS CarriersDetails_UNIQUE_CARRIER_NAME
    , CD.[WAC] AS CarriersDetails_WAC
    , CD.[CARRIER_GROUP] AS CarriersDetails_CARRIER_GROUP
    , CD.[CARRIER_GROUP_NEW] AS CarriersDetails_CARRIER_GROUP_NEW
    , CD.[REGION_LONG] AS CarriersDetails_REGION_LONG
    , CD.[REGION] AS CarriersDetails_REGION
    , CD.[START_DATE_SOURCE] AS CarriersDetails_START_DATE_SOURCE
    , CD.[THRU_DATE_SOURCE] AS CarriersDetails_THRU_DATE_SOURCE
    , CD.[FK_CARRIER_ID] AS CarriersDetails_FK_CARRIER_ID
-- Aircrafts_Type_Lookup
    , ATL.[SK_ID] AS Aircrafttypelookup_SK_ID
    , ATL.[AIRCRAFT_TYPE] AS Aircrafttypelookup_AIRCRAFT_TYPE
    , ATL.[DESCRIPTION] AS Aircrafttypelookup_DESCRIPTION
-- FARES_DETAILS
    , FD.[BK_QYEAR_ORI_DEST] AS Fares_Details_BK_QYEAR_ORI_DEST
    , FD.[MODE_FARE] AS Fares_Details_MODE_FARE
    , FD.[AVG_MARKET_DISTANCE] AS Fares_Details_AVG_MARKET_DISTANCE
-- Distrance_GROUP
    , DG.[BK_Code] AS Distance_Group_BK_Code
    , DG.[DESCRIPTION] AS Distance_Group_DESCRIPTION
-- Service_Class
    , SC.[BK_Code] AS Service_Class_BK_Code
    , SC.[DESCRIPTION] AS Service_Class_DESCRIPTION
-- Aircraft_Group
    ,AG.[BK_Code] AS Aircraft_Group_BK_Code
    , AG.[DESCRIPTION] AS Aircraft_Group_DESCRIPTION
    , CASE 
        WHEN T100.[DEPARTURES_PERFORMED] = 0 THEN 0 
        ELSE CAST(T100.[PASSENGERS] / T100.[DEPARTURES_PERFORMED] AS FLOAT)
      END AS AVG_PASSENGERS_FLIGHT
    , CASE
    WHEN T100.[SEATS] = 0 THEN '0.00'
    ELSE FORMAT((CAST(T100.[PASSENGERS] AS DECIMAL(10, 4)) / T100.[SEATS]) * 100, 'N2')
      END AS T100_PASSENGERS_LOADFACTOR_PCT
FROM Fact_T100 T100
LEFT JOIN Airports Aorig ON Aorig.AIRPORT_SEQ_ID = T100.SK_ORIGIN_AIRPORT_SEQ_ID
LEFT JOIN Airports Adest ON Adest.AIRPORT_SEQ_ID = T100.SK_DEST_AIRPORT_SEQ_ID
LEFT JOIN Carriers_Details CD ON CD.SK_ID = T100.SK_UNIQUE_CARRIER_ENTITY
LEFT JOIN Aircrafts_Type_Lookup ATL ON ATL.SK_ID = T100.SK_AIRCRAFT_CODE
LEFT JOIN FARES_DETAILS FD ON FD.BK_QYEAR_ORI_DEST =  T100.BK_QYEAR_ORI_DEST
LEFT JOIN Distance_GROUP DG ON DG.BK_Code = T100.DISTANCE_GROUP
LEFT JOIN Service_Class SC ON SC.BK_Code = T100.CLASS
LEFT JOIN Aircraft_Group AG ON AG.BK_Code = T100.AIRCRAFT_GROUP
GO


